name: Release Gem

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # required for RubyGems trusted publishing

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Release to RubyGems
        uses: rubygems/release-gem@v1
